Harvardinformatics bam2wig
Gaius-Augustus/Augustus pull request #216
Opened 2020-11-17 16:15 UTC by hmehlan

This PR replaces #153 ; 
rather than removing bam2wig completely (which is not desirable for all use cases, as it's more efficient than bamToWig.py), this PR provides modifications that make it easier to build; specifically, only htslib (>= 1.10.0) is required rather than also requiring (source builds of) bcftools and samtools.
ubuntu 20.04 and debian 11 alternatively provide the package libhts-dev.

2020-12-04 19:29 UTC, MarioStanke commented on tests/auxprogs/bam2wig/test_bam2wig.py
> +from tests.utils import aug_assertions
```    
from tests.utils import aug_assertions
ModuleNotFoundError: No module named 'tests.utils'
```

2020-12-04 19:29 UTC, MarioStanke commented on tests/utils/aug_argparse.py
> +    return parser
```suggestion
    return parser
    
```

2020-12-04 19:30 UTC, MarioStanke requested changes
make clean requires Python now. I suspect some dependencies may not be necessary to delete files and the dependency can be dropped.
In any case,  the required python module for testing does not appear to be mentioned as a requirement to run tests. 


```
# make clean
tests/auxprogs/bam2wig/test_bam2wig.py --clean
Traceback (most recent call last):
  File "tests/auxprogs/bam2wig/test_bam2wig.py", line 13, in <module>
    from tests.utils import aug_assertions
ModuleNotFoundError: No module named 'tests.utils'

```

no newline at end of aug_assertions.py, aug_path.py, aug_process.py.

2020-12-04 19:31 UTC, MarioStanke commented on tests/auxprogs/bam2wig/test_bam2wig.py
> +from tests.utils import aug_assertions
I ran `make clean` in the top-level dir.

2020-12-07 13:35 UTC, hmehlan commented on tests/utils/aug_argparse.py
> +    return parser
newline added

2020-12-09 11:10 UTC, MarioStanke approved these changes

2020-12-09 11:10 UTC, merged